name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run
        run: |
          echo $SETTINGS_XML | base64 -d > settings.xml
          mvn -s settings.xml package exec:java
        env:
          SETTINGS_XML: ${{ secrets.SETTINGSXML }}